# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.jenkins-ci.main:jenkins-bom"
      - dependency-name: "org.jenkins-ci.main:jenkins-core"
      - dependency-name: "org.jenkins-ci.main:jenkins-war"
      # see https://github.com/apache/maven-surefire/issues/2601
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
